### PR TITLE
Defect Dojo integration

### PR DESCRIPTION
**Pull request by syn-4ck**
Hi!

Related with #157 

> NOTE: Please, verify the changes (It is working in my local host, but it could be great that you can modify/review/test it well). Thanks!

### CODE REVIEW

**Comment by aronmolnar** [comment]
Great, thank you. We'll do.

**Comment by syn-4ck** [comment]
Thanks @aronmolnar. Excelent work! Nice tool 👏

**Comment by aronmolnar** [comment]
Well done, thank you for your contribution.

I made a few adaptions, e.g., the DefectDojo results are paginated and there was a loop missing, and fixes.
Can you try if you are able to migrate your findings with this version?

**Comment by syn-4ck** [comment]
Oh, my bad... Thanks for your work! I'm gonna try now, but I can't se changes... where is this changes applied?

**Comment by aronmolnar** [comment]
Ah, sorry - I of course, couldn't push to your fork.
Changes are in this branch: https://github.com/Syslifters/reptor/tree/syn-4ck-main

**Comment by syn-4ck** [comment]
Perfect! Testing now :)

**Comment by syn-4ck** [comment]
Hi @aronmolnar, I put 4 comments in https://github.com/Syslifters/reptor/commit/cf0512b5776f8bd334e529721b047835252f7f36.

Some of this changes I can fix locally, and I put my recommendation, but I can't fix the last one: https://github.com/Syslifters/reptor/commit/cf0512b5776f8bd334e529721b047835252f7f36#r139247341

Could you help me to push the other 3 fixes and investigate the error in the last one?

Thanks for your support :)

**Comment by aronmolnar** [comment]
Thanks for your feedback.  
Updated the branch.

Can you try out the next round?

**Comment by syn-4ck** [comment]
Hi @aronmolnar, working great! LGTM :).

**Comment by syn-4ck** [comment]
Hi @aronmolnar, is It better merge the syn-4ck-main branch?

**Comment by aronmolnar** [comment]
> Hi @aronmolnar, is It better merge the syn-4ck-main branch?

Yes, my bad.

**Pull request merged**
